import type { IndustryPack } from "../types"

export const bridal: IndustryPack = {
  id: "bridal",
  label: "בוטיק שמלות כלה",
  mode: "listings",
  vocab: {
    person: "כלה",
    people: "כלות",
    booking: "מדידה",
    bookings: "מדידות",
    deal: "הזמנה",
    dealsTitle: "הזמנות אחרונות",
    catalog: "קולקציה",
    catalogItem: "שמלה",
    revenue: "הכנסה שנסגרה",
    upcoming: "מדידות והתאמות",
  },
  stages: [
    { id: "new", label: "פנייה חדשה", probability: 0.1 },
    { id: "fitting", label: "פגישת מדידה", probability: 0.35 },
    { id: "chosen", label: "בחרה שמלה", probability: 0.65 },
    { id: "deposit", label: "הזמנה + מקדמה", probability: 0.9 },
    { id: "alter", label: "התאמות", probability: 0.95 },
    { id: "done", label: "נמסרה ושולמה", probability: 1 },
  ],
  bookedFromStage: 1,
  fields: [
    { key: "date", label: "מועד החתונה", icon: "calendar", options: ["בעוד 3 חודשים", "בעוד 6 חודשים", "בעוד 9 חודשים", "בעוד שנה"] },
    { key: "style", label: "סגנון מועדף", icon: "heart", options: ["קלאסי", "בוהו", "מינימליסטי", "נסיכה"] },
    { key: "budget", label: "תקציב", icon: "wallet", options: ["עד 6,000 ₪", "6,000–10,000 ₪", "מעל 10,000 ₪"] },
  ],
  catalogIcon: "gem",
  valueFactor: 1,
  brand: {
    accent: "#8b6446",
    accent2: "#5f7066",
    warm: "#ead9a3",
    ink: "#17120e",
    bgFrom: "#f0e4d8",
    bgTo: "#e0e9e2",
  },
  catalog: [
    { title: "A-line משי · ‘אורה’", subtitle: "קו נקי, גב פתוח", price: 11800, tags: ["קלאסי"], meta: [{ label: "צבע", value: "שנהב" }, { label: "מידות", value: "34–44" }], photos: 9, status: "hot", sent: 44 },
    { title: "תחרה צרפתית · ‘לילי’", subtitle: "שרוולי תחרה עדינים", price: 13900, tags: ["רומנטי"], meta: [{ label: "צבע", value: "שמפניה" }, { label: "מידות", value: "34–42" }], photos: 12, status: "available", sent: 31 },
    { title: "נסיכה בטול · ‘אמה’", subtitle: "חצאית מלאה, מחוך מחוזק", price: 9600, tags: ["נסיכה"], meta: [{ label: "צבע", value: "לבן" }, { label: "מידות", value: "34–46" }], photos: 8, status: "available", sent: 27 },
    { title: "סאטן מינימליסטי · ‘נועה’", subtitle: "בלי קישוטים, חיתוך מושלם", price: 8400, tags: ["מינימליסטי"], meta: [{ label: "צבע", value: "שנהב" }, { label: "מידות", value: "34–44" }], photos: 7, status: "reserved", sent: 22 },
    { title: "בוהו עם שרוולים · ‘שיר’", subtitle: "קל, מתאים לחוץ ולחוף", price: 7200, tags: ["בוהו"], meta: [{ label: "צבע", value: "שמנת" }, { label: "מידות", value: "34–42" }], photos: 10, status: "available", sent: 36 },
    { title: "קורסט תחרה · ‘דנה’", subtitle: "מחוך מעוצב, זנב קצר", price: 12600, tags: ["קלאסי"], meta: [{ label: "צבע", value: "שנהב" }, { label: "מידות", value: "34–44" }], photos: 11, status: "available", sent: 19 },
  ],
  appointmentLabels: ["פגישת מדידה", "מדידת התאמות", "מדידה שנייה", "מסירת שמלה"],
  slotMinutes: 90,
  openers: [
    "היי, מתחתנת בעוד חצי שנה. ראיתי את {item}, אפשר לראות?",
    "יש את {item} במידה 38?",
    "כמה עולה {item}?",
    "אפשר להגיע למדידה של {item} עם אמא ושתי חברות?",
    "מה התקציב הממוצע? מתעניינת ב{item}",
  ],
  reply: "מזל טוב! {item} — {price}. שולחת תמונות. אפשר לקבוע מדידה {slot}. מתאים?",
  confirm: "קבעתי מדידה ל{slot}. נכין את השמלות מראש, ושתייה על החשבוננו 🥂",
  close: "אפשר להגיע עד 4 אורחות. שולחת תזכורת יום לפני.",
  tags: ["כלה", "מדידה שנייה", "מהר — חתונה קרובה", "המלצה"],
  knowledge: ["קולקציה ותמונות שמלות", "מחירים ומידות", "תהליך הזמנה והתאמות", "יומן מדידות", "תנאי מקדמה"],
}
