import type { IndustryPack } from "../types"

export const chef: IndustryPack = {
  id: "chef",
  label: "שף פרטי",
  mode: "projects",
  vocab: {
    person: "לקוח/ה",
    people: "לקוחות",
    booking: "אירוע",
    bookings: "אירועים",
    deal: "אירוע",
    dealsTitle: "אירועים אחרונים",
    catalog: "תפריטים",
    catalogItem: "תפריט",
    revenue: "הכנסה שנסגרה",
    upcoming: "טעימות ואירועים",
  },
  stages: [
    { id: "new", label: "פנייה חדשה", probability: 0.1 },
    { id: "tasting", label: "טעימות", probability: 0.35 },
    { id: "quote", label: "הצעת מחיר", probability: 0.55 },
    { id: "deposit", label: "מקדמה שולמה", probability: 0.85 },
    { id: "event", label: "האירוע התקיים", probability: 0.95 },
    { id: "done", label: "נסגר ושולם", probability: 1 },
  ],
  bookedFromStage: 1,
  fields: [
    { key: "eventType", label: "סוג אירוע", icon: "utensils", options: ["ארוחת שישי", "יום הולדת", "אירוע חברה", "חתונה אינטימית", "ארוחה רומנטית"] },
    { key: "guests", label: "מספר סועדים", icon: "users", options: ["6", "10", "14", "20", "35"] },
    { key: "diet", label: "מגבלות תזונה", icon: "leaf", options: ["ללא", "צמחוני", "טבעוני", "ללא גלוטן", "כשר למהדרין"] },
  ],
  catalogIcon: "utensils",
  valueFactor: 1,
  valueByField: "guests",
  brand: {
    accent: "#e4572e",
    accent2: "#2f6b5a",
    warm: "#f2c14e",
    ink: "#161210",
    bgFrom: "#f6dcc6",
    bgTo: "#e7ecd5",
  },
  catalog: [
    { title: "תפריט טעימות — 5 מנות", subtitle: "שולחן עם פיירינג יין", price: 380, priceSuffix: "לסועד", tags: ["פרימיום"], meta: [{ label: "משך", value: "3 שעות" }], photos: 18, status: "hot", sent: 52 },
    { title: "ארוחת שישי משפחתית", subtitle: "מסורת בעיבוד מודרני", price: 290, priceSuffix: "לסועד", tags: ["משפחתי"], meta: [{ label: "משך", value: "הכנה במקום" }], photos: 12, status: "available", sent: 38 },
    { title: "קוקטייל ומנות אצבע", subtitle: "לאירוע עומד", price: 210, priceSuffix: "לסועד", tags: ["אירוע"], meta: [{ label: "מינימום", value: "20 איש" }], photos: 14, status: "available", sent: 21 },
    { title: "שולחן חג", subtitle: "פסח, ראש השנה, שבועות", price: 340, priceSuffix: "לסועד", tags: ["חגים"], meta: [{ label: "הזמנה", value: "חודש מראש" }], photos: 9, status: "available", sent: 17 },
    { title: "ארוחה רומנטית לזוג", subtitle: "אצלכם בבית, כולל הגשה", price: 1800, priceSuffix: "לזוג", tags: ["זוגי"], meta: [{ label: "משך", value: "2.5 שעות" }], photos: 8, status: "available", sent: 26 },
    { title: "סדנת בישול פרטית", subtitle: "לקבוצה עד 12 איש", price: 4200, priceSuffix: "לקבוצה", tags: ["חוויה"], meta: [{ label: "משך", value: "3 שעות" }], photos: 11, status: "available", sent: 14 },
  ],
  appointmentLabels: ["טעימות בבית הלקוח", "פגישת תפריט", "האירוע", "סיור במטבח"],
  slotMinutes: 120,
  openers: [
    "שלום, אשמח לפרטים על {item}. כמה זה יוצא?",
    "אפשר פרטים על {item}? מדובר בבערך 14 איש",
    "ראיתי בתפריט את {item}, אפשר הצעה?",
    "מחפשים שף לאירוע, {item} נשמע לנו מתאים",
    "אתם מגיעים עד חיפה עם {item}?",
  ],
  reply: "היי! {item} — {price}. אפשר לתאם טעימות {slot}, ואז נסגור הצעה סופית. מתאים?",
  confirm: "סגרנו. הטעימות נקבעו ל{slot}. אשלח שאלון קצר על העדפות ואלרגיות.",
  close: "מחכה לראות אתכם. אשלח הצעת מחיר מסודרת מיד אחרי הטעימות.",
  tags: ["שבת", "ללא גלוטן", "חוזר", "המלצה"],
  knowledge: ["תפריטים ותמונות מנות", "אזורי הגעה ועלויות", "אלרגיות והתאמות", "יומן אירועים פנוי", "תנאי מקדמה וביטול"],
}
