import type { IndustryPack } from "../types"

export const contractor: IndustryPack = {
  id: "contractor",
  label: "שיפוצים וקבלנות",
  mode: "projects",
  vocab: {
    person: "לקוח/ה",
    people: "לקוחות",
    booking: "סיור",
    bookings: "סיורים",
    deal: "פרויקט",
    dealsTitle: "פרויקטים אחרונים",
    catalog: "סוגי עבודות",
    catalogItem: "עבודה",
    revenue: "הכנסה שנסגרה",
    upcoming: "סיורי הצעה",
  },
  stages: [
    { id: "new", label: "פנייה חדשה", probability: 0.05 },
    { id: "visit", label: "סיור והערכה", probability: 0.25 },
    { id: "quote", label: "הצעת מחיר", probability: 0.45 },
    { id: "signed", label: "חתם + מקדמה", probability: 0.9 },
    { id: "work", label: "בביצוע", probability: 0.95 },
    { id: "done", label: "הושלם ושולם", probability: 1 },
  ],
  bookedFromStage: 1,
  fields: [
    { key: "job", label: "סוג עבודה", icon: "hammer", options: ["מטבח", "חדר רחצה", "ריצוף", "צבע ושפכטל", "שיפוץ כללי"] },
    { key: "size", label: "גודל הנכס", icon: "ruler", options: ["עד 60 מ״ר", "60–90 מ״ר", "90–120 מ״ר", "מעל 120 מ״ר"] },
    { key: "when", label: "לוח זמנים", icon: "calendar", options: ["דחוף — חודש", "1–3 חודשים", "גמיש"] },
  ],
  catalogIcon: "hammer",
  valueFactor: 1,
  brand: {
    accent: "#a25a16",
    accent2: "#3a6ea5",
    warm: "#f2d349",
    ink: "#14110d",
    bgFrom: "#ecdcc7",
    bgTo: "#d8e3ee",
  },
  catalog: [
    { title: "שיפוץ מטבח מלא", subtitle: "פירוק, חשמל, אינסטלציה, נגרות", price: 48000, tags: ["מטבח"], meta: [{ label: "משך", value: "4–6 שבועות" }], photos: 16, status: "hot", sent: 39 },
    { title: "שיפוץ חדר רחצה", subtitle: "איטום, ריצוף, כלים סניטריים", price: 32000, tags: ["רחצה"], meta: [{ label: "משך", value: "3–4 שבועות" }], photos: 14, status: "available", sent: 44 },
    { title: "החלפת ריצוף לדירה", subtitle: "דירת 4 חדרים, כולל פירוק", price: 36000, tags: ["ריצוף"], meta: [{ label: "משך", value: "2–3 שבועות" }], photos: 9, status: "available", sent: 21 },
    { title: "צביעה ושפכטל", subtitle: "כל הדירה, שני צבעים", price: 14000, tags: ["צבע"], meta: [{ label: "משך", value: "5–7 ימים" }], photos: 8, status: "available", sent: 30 },
    { title: "שיפוץ כללי לדירה", subtitle: "מפתח ביד, ניהול פרויקט", price: 120000, tags: ["מלא"], meta: [{ label: "משך", value: "10–14 שבועות" }], photos: 22, status: "available", sent: 17 },
  ],
  appointmentLabels: ["סיור והערכה", "פגישת הצעת מחיר", "בחירת חומרים", "תחילת עבודות"],
  slotMinutes: 60,
  openers: [
    "שלום, אשמח לפרטים על {item}. כמה זה יוצא?",
    "אפשר הצעת מחיר ל{item}?",
    "צריך {item} בדירה בראשון לציון",
    "כמה זמן לוקח {item}?",
    "אפשר סיור לפני {item}?",
  ],
  reply: "שלום! {item} — החל מ-{price}. אפשר לתאם סיור הערכה {slot}. מתאים?",
  confirm: "קבעתי סיור ל{slot}. כדאי לצלם את החלל ולשלוח לי כבר עכשיו.",
  close: "אחרי הסיור נשלח הצעת מחיר מסודרת תוך 48 שעות.",
  tags: ["דחוף", "אדריכל", "דירה חדשה", "המלצה"],
  knowledge: ["סוגי עבודות ומחירי התחלה", "גלריית פרויקטים", "אזורי שירות", "לוחות זמנים", "תנאי תשלום ואחריות"],
}
