import type { IndustryPack } from "../types"

export const dental: IndustryPack = {
  id: "dental",
  label: "מרפאת שיניים",
  mode: "appointments",
  vocab: {
    person: "מטופל/ת",
    people: "מטופלים",
    booking: "תור",
    bookings: "תורים",
    deal: "טיפול",
    dealsTitle: "טיפולים אחרונים",
    catalog: "טיפולים",
    catalogItem: "טיפול",
    revenue: "הכנסה שנסגרה",
    upcoming: "תורים קרובים",
  },
  stages: [
    { id: "new", label: "פנייה חדשה", probability: 0.1 },
    { id: "booked", label: "תור נקבע", probability: 0.35 },
    { id: "visited", label: "הגיע לייעוץ", probability: 0.55 },
    { id: "plan", label: "תוכנית טיפול", probability: 0.75 },
    { id: "treating", label: "בטיפול", probability: 0.9 },
    { id: "done", label: "הושלם ושולם", probability: 1 },
  ],
  bookedFromStage: 1,
  fields: [
    { key: "treatment", label: "סוג טיפול", icon: "stethoscope", options: ["ייעוץ ובדיקה", "הלבנה", "שתל", "יישור שקוף", "טיפול שורש", "סתימה"] },
    { key: "insurance", label: "קופה / ביטוח", icon: "shield", options: ["מכבי שיניים", "כללית מושלם", "מאוחדת עדיף", "פרטי", "ביטוח משלים"] },
    { key: "anxiety", label: "חשש מטיפולים", icon: "heart", options: ["ללא", "קל", "גבוה — לקבוע זמן ארוך"] },
  ],
  catalogIcon: "stethoscope",
  valueFactor: 1,
  brand: {
    accent: "#2f4bff",
    accent2: "#3f8f9e",
    warm: "#f2e24a",
    ink: "#0d0d0d",
    bgFrom: "#cbd7f2",
    bgTo: "#e3efdc",
  },
  catalog: [
    { title: "ייעוץ ובדיקה ראשונית", subtitle: "כולל צילום פנורמי", price: 250, tags: ["חדשים"], meta: [{ label: "משך", value: "40 דק׳" }], photos: 0, status: "available", sent: 41 },
    { title: "הלבנת שיניים בלייזר", subtitle: "תוצאה תוך שעה", price: 1400, tags: ["אסתטיקה"], meta: [{ label: "משך", value: "60 דק׳" }], photos: 8, status: "hot", sent: 63 },
    { title: "ניקוי אבן וטיפול הגיינה", subtitle: "מומלץ כל 6 חודשים", price: 420, tags: ["מניעה"], meta: [{ label: "משך", value: "45 דק׳" }], photos: 0, status: "available", sent: 28 },
    { title: "סתימה אסתטית", subtitle: "חומר בצבע השן", price: 650, tags: ["שיקום"], meta: [{ label: "משך", value: "45 דק׳" }], photos: 3, status: "available", sent: 19 },
    { title: "טיפול שורש", subtitle: "בהרדמה מלאה, ללא כאב", price: 1800, tags: ["שיקום"], meta: [{ label: "משך", value: "90 דק׳" }], photos: 0, status: "available", sent: 22 },
    { title: "שתל שן + כתר", subtitle: "כולל תוכנית טיפול מלאה", price: 7400, tags: ["שתלים"], meta: [{ label: "משך", value: "3 מפגשים" }], photos: 14, status: "hot", sent: 17 },
    { title: "יישור שיניים שקוף", subtitle: "ללא פלטות מתכת", price: 14500, tags: ["אורתודונטיה"], meta: [{ label: "משך", value: "8–14 חודשים" }], photos: 12, status: "available", sent: 24 },
  ],
  appointmentLabels: ["ייעוץ ובדיקה", "הלבנה", "טיפול שורש", "ניקוי אבן", "פגישת תוכנית טיפול"],
  slotMinutes: 45,
  openers: [
    "היי, כמה עולה {item}?",
    "אפשר מחיר על {item}?",
    "אשמח להבין איך {item} עובד",
    "יש מקום השבוע ל{item}?",
    "שלום, אשמח לפרטים על {item}",
  ],
  reply: "שלום! {item} אצלנו — {price}. יש לי פנוי {slot}. מתאים?",
  confirm: "קבעתי ל{slot}. שולח כתובת והנחיות הגעה.",
  close: "נשלח תזכורת יום לפני. אפשר לשנות בכל רגע בהודעה כאן.",
  tags: ["דחוף", "הפניה", "ילדים", "פחד משיניים"],
  knowledge: ["מחירון טיפולים", "שעות פעילות ויומן", "קופות חולים וביטוחים", "הנחיות לפני ואחרי טיפול", "כתובת והנחיות הגעה"],
}
