import type { IndustryPack } from "../types"

export const fitness: IndustryPack = {
  id: "fitness",
  label: "סטודיו כושר ואימון אישי",
  mode: "appointments",
  vocab: {
    person: "מתאמן/ת",
    people: "מתאמנים",
    booking: "אימון",
    bookings: "אימונים",
    deal: "מנוי",
    dealsTitle: "הצטרפויות אחרונות",
    catalog: "מסלולים",
    catalogItem: "מסלול",
    revenue: "הכנסה שנסגרה",
    upcoming: "אימוני ניסיון",
  },
  stages: [
    { id: "new", label: "פנייה חדשה", probability: 0.1 },
    { id: "trial", label: "אימון ניסיון", probability: 0.45 },
    { id: "offer", label: "הצעת מסלול", probability: 0.65 },
    { id: "joined", label: "נרשם/ה", probability: 0.95 },
    { id: "active", label: "מנוי פעיל", probability: 1 },
  ],
  bookedFromStage: 1,
  fields: [
    { key: "goal", label: "מטרה", icon: "dumbbell", options: ["חיטוב", "עלייה במסה", "שיקום", "הכנה לחתונה", "כושר כללי"] },
    { key: "level", label: "רמה", icon: "heart", options: ["מתחיל/ה", "בינוני", "מתקדם"] },
    { key: "time", label: "שעות מועדפות", icon: "clock", options: ["בוקר מוקדם", "צהריים", "ערב"] },
  ],
  catalogIcon: "dumbbell",
  valueFactor: 1,
  brand: {
    accent: "#bd4322",
    accent2: "#1f7a5c",
    warm: "#e4ef4a",
    ink: "#120e0c",
    bgFrom: "#fbddd0",
    bgTo: "#e1eed6",
  },
  catalog: [
    { title: "מנוי קבוצתי חודשי", subtitle: "אימונים ללא הגבלה", price: 390, priceSuffix: "לחודש", tags: ["קבוצתי"], meta: [{ label: "אימונים", value: "ללא הגבלה" }], photos: 6, status: "hot", sent: 52 },
    { title: "כרטיסיית אימונים אישיים", subtitle: "10 אימונים עם מאמן", price: 1800, tags: ["אישי"], meta: [{ label: "תוקף", value: "4 חודשים" }], photos: 4, status: "available", sent: 33 },
    { title: "ליווי תזונה 12 שבועות", subtitle: "תפריט ומעקב שבועי", price: 1500, tags: ["תזונה"], meta: [{ label: "משך", value: "12 שבועות" }], photos: 3, status: "available", sent: 18 },
    { title: "חבילת חתן וכלה", subtitle: "8 שבועות לקראת החתונה", price: 2400, tags: ["אירוע"], meta: [{ label: "משך", value: "8 שבועות" }], photos: 5, status: "available", sent: 14 },
    { title: "פילאטיס מכשירים", subtitle: "8 מפגשים בקבוצה קטנה", price: 1100, tags: ["פילאטיס"], meta: [{ label: "מפגשים", value: "8" }], photos: 7, status: "available", sent: 24 },
  ],
  appointmentLabels: ["אימון ניסיון", "פגישת התאמת מסלול", "מדידות ויעדים"],
  slotMinutes: 60,
  openers: [
    "היי, כמה עולה {item}?",
    "אפשר אימון ניסיון לפני {item}?",
    "אשמח לדעת איך {item} עובד",
    "יש {item} בשעות הערב?",
    "אני אחרי פציעה, {item} מתאים?",
  ],
  reply: "היי! {item} — {price}. אימון ניסיון {slot}, בלי התחייבות. מתאים?",
  confirm: "קבעתי ל{slot}. בואו עם בגדי ספורט ובקבוק מים 💪",
  close: "אשלח תזכורת שעתיים לפני עם הכתובת.",
  tags: ["כלה/חתן", "שיקום", "מנוי חוזר", "חבר מביא חבר"],
  knowledge: ["מסלולים ומחירים", "לוח אימונים", "מאמנים והתמחויות", "מדיניות הקפאה וביטול", "כתובת וחניה"],
}
