import type { IndustryPack } from "../types"

export const makeup: IndustryPack = {
  id: "makeup",
  label: "קליניקת איפור",
  mode: "projects",
  vocab: {
    person: "לקוחה",
    people: "לקוחות",
    booking: "תור",
    bookings: "תורים",
    deal: "הזמנה",
    dealsTitle: "הזמנות אחרונות",
    catalog: "חבילות",
    catalogItem: "חבילה",
    revenue: "הכנסה שנסגרה",
    upcoming: "ניסיונות ואירועים",
  },
  stages: [
    { id: "new", label: "פנייה חדשה", probability: 0.1 },
    { id: "trial", label: "ניסיון איפור", probability: 0.4 },
    { id: "quote", label: "הצעה נשלחה", probability: 0.6 },
    { id: "deposit", label: "מקדמה שולמה", probability: 0.9 },
    { id: "event", label: "יום האירוע", probability: 0.95 },
    { id: "done", label: "נסגר ושולם", probability: 1 },
  ],
  bookedFromStage: 1,
  fields: [
    { key: "event", label: "סוג אירוע", icon: "sparkles", options: ["חתונה", "חינה", "בת מצווה", "צילומים", "ערב"] },
    { key: "where", label: "מיקום האיפור", icon: "map-pin", options: ["בסטודיו", "בבית הכלה", "באולם", "בחדר במלון"] },
    { key: "people", label: "נשים לאיפור", icon: "users", options: ["1", "3", "5", "8"] },
  ],
  catalogIcon: "palette",
  valueFactor: 1,
  brand: {
    accent: "#c52f63",
    accent2: "#8354c0",
    warm: "#f7c65a",
    ink: "#150d12",
    bgFrom: "#f4d3e2",
    bgTo: "#e3def6",
  },
  catalog: [
    { title: "איפור כלה + ניסיון", subtitle: "כולל ליווי ביום החתונה", price: 2400, tags: ["כלות"], meta: [{ label: "משך", value: "ניסיון + יום האירוע" }], photos: 22, status: "hot", sent: 46 },
    { title: "איפור ערב", subtitle: "מראה מלוטש לאירוע", price: 650, tags: ["ערב"], meta: [{ label: "משך", value: "75 דק׳" }], photos: 15, status: "available", sent: 34 },
    { title: "איפור לבת מצווה", subtitle: "טבעי ונוצץ בדיוק במידה", price: 480, tags: ["נוער"], meta: [{ label: "משך", value: "60 דק׳" }], photos: 10, status: "available", sent: 19 },
    { title: "חבילת אירוע: אמא וחברות", subtitle: "עד 5 נשים באותו בוקר", price: 1900, tags: ["קבוצתי"], meta: [{ label: "נשים", value: "עד 5" }], photos: 12, status: "available", sent: 22 },
    { title: "איפור לצילומים", subtitle: "סטודיו או לוקיישן", price: 750, tags: ["צילום"], meta: [{ label: "משך", value: "90 דק׳" }], photos: 9, status: "available", sent: 11 },
    { title: "סדנת איפור עצמי", subtitle: "פרטית, עם מוצרים שלך", price: 900, tags: ["סדנה"], meta: [{ label: "משך", value: "2 שעות" }], photos: 6, status: "available", sent: 16 },
  ],
  appointmentLabels: ["ניסיון איפור", "איפור ערב", "יום האירוע", "ייעוץ מראה"],
  slotMinutes: 90,
  openers: [
    "היי! אשמח לפרטים על {item}",
    "כמה עולה {item}?",
    "ראיתי באינסטגרם את העבודות, מתעניינת ב{item}",
    "יש תאריך פנוי בחורף ל{item}?",
    "אתן מגיעות עד הבית? מתעניינת ב{item}",
  ],
  reply: "איזה כיף! {item} — {price}. אפשר לתאם ניסיון {slot}. מתאים?",
  confirm: "קבעתי ניסיון ל{slot}. שולחת תמונות השראה כדי שתבחרי כיוון.",
  close: "נתראה! אשלח תזכורת יום לפני עם הנחיות להגעה עם פנים נקיות.",
  tags: ["כלה", "חוזרת", "המלצה", "VIP"],
  knowledge: ["חבילות ומחירים", "גלריית עבודות", "יומן פנוי לעונת האירועים", "אזורי הגעה", "תנאי מקדמה וביטול"],
}
