import type { IndustryPack } from "../types"

export const nails: IndustryPack = {
  id: "nails",
  label: "סטודיו ללק ג׳ל",
  mode: "appointments",
  vocab: {
    person: "לקוחה",
    people: "לקוחות",
    booking: "תור",
    bookings: "תורים",
    deal: "טיפול",
    dealsTitle: "טיפולים אחרונים",
    catalog: "טיפולים",
    catalogItem: "טיפול",
    revenue: "הכנסה שנסגרה",
    upcoming: "תורים קרובים",
  },
  stages: [
    { id: "new", label: "פנייה חדשה", probability: 0.2 },
    { id: "booked", label: "תור נקבע", probability: 0.6 },
    { id: "visited", label: "הגיעה לטיפול", probability: 0.9 },
    { id: "second", label: "תור שני נקבע", probability: 0.95 },
    { id: "regular", label: "לקוחה קבועה", probability: 1 },
  ],
  bookedFromStage: 1,
  fields: [
    { key: "service", label: "סוג טיפול", icon: "sparkles", options: ["לק ג׳ל", "בנייה בג׳ל", "אקריליק", "פדיקור", "הסרה וטיפול"] },
    { key: "length", label: "אורך", icon: "ruler", options: ["קצר", "בינוני", "ארוך", "XL"] },
    { key: "style", label: "סגנון", icon: "palette", options: ["צרפתי", "נוּד", "כרום", "צבעוני", "עיצוב אישי"] },
  ],
  catalogIcon: "sparkles",
  valueFactor: 1,
  brand: {
    accent: "#7c5cff",
    accent2: "#ff7aa8",
    warm: "#ffd166",
    ink: "#120d1c",
    bgFrom: "#e2d9f8",
    bgTo: "#f9dfe9",
  },
  catalog: [
    { title: "לק ג׳ל", subtitle: "ידיים, כולל הכנה", price: 150, tags: ["בסיס"], meta: [{ label: "משך", value: "60 דק׳" }], photos: 24, status: "hot", sent: 88 },
    { title: "בנייה בג׳ל", subtitle: "הארכה וחיזוק", price: 220, tags: ["בנייה"], meta: [{ label: "משך", value: "90 דק׳" }], photos: 31, status: "available", sent: 61 },
    { title: "אקריליק", subtitle: "אורך וצורה לבחירה", price: 260, tags: ["בנייה"], meta: [{ label: "משך", value: "100 דק׳" }], photos: 19, status: "available", sent: 37 },
    { title: "פדיקור + לק", subtitle: "כולל עיסוי רגליים", price: 200, tags: ["רגליים"], meta: [{ label: "משך", value: "75 דק׳" }], photos: 12, status: "available", sent: 29 },
    { title: "עיצוב אומנותי", subtitle: "תוספת לכל טיפול, לפי ציפורן", price: 60, tags: ["תוספת"], meta: [{ label: "משך", value: "+20 דק׳" }], photos: 46, status: "hot", sent: 74 },
    { title: "הסרה וטיפול", subtitle: "הסרה עדינה והזנה", price: 120, tags: ["טיפול"], meta: [{ label: "משך", value: "45 דק׳" }], photos: 4, status: "available", sent: 18 },
  ],
  appointmentLabels: ["לק ג׳ל", "בנייה בג׳ל", "פדיקור + לק", "אקריליק"],
  slotMinutes: 75,
  openers: [
    "היי, כמה עולה {item}?",
    "יש תור לשבוע הבא ל{item}?",
    "אפשר לראות עיצובים? מתעניינת ב{item}",
    "מתי הכי קרוב פנוי ל{item}?",
    "אפשר להגיע עם חברה ל{item}?",
  ],
  reply: "היי יפה! {item} — {price}. הכי קרוב פנוי {slot}. מתאים?",
  confirm: "סגור, קבעתי ל{slot} 💅 שולחת לך כתובת וחניה.",
  close: "אשלח תזכורת יום לפני. אם צריך לשנות, פשוט תכתבי כאן.",
  tags: ["קבועה", "חדשה", "עיצוב אישי", "מבצע"],
  knowledge: ["מחירון טיפולים", "גלריית עיצובים", "יומן פנוי", "מדיניות איחורים וביטולים", "כתובת וחניה"],
}
