import type { IndustryPack } from "../types"

export const realestate: IndustryPack = {
  id: "realestate",
  label: "נדל״ן ותיווך",
  mode: "listings",
  vocab: {
    person: "מתעניין/ת",
    people: "מתעניינים",
    booking: "סיור",
    bookings: "סיורים",
    deal: "עסקה",
    dealsTitle: "עסקאות אחרונות",
    catalog: "נכסים",
    catalogItem: "נכס",
    revenue: "עמלות שנסגרו",
    upcoming: "סיורים קרובים",
  },
  stages: [
    { id: "new", label: "ליד חדש", probability: 0.05 },
    { id: "qualified", label: "סינון וצורך", probability: 0.15 },
    { id: "tour", label: "סיור בנכס", probability: 0.35 },
    { id: "offer", label: "הצעה ומו״מ", probability: 0.6 },
    { id: "contract", label: "חוזה בהכנה", probability: 0.9 },
    { id: "done", label: "עסקה נסגרה", probability: 1 },
  ],
  bookedFromStage: 2,
  fields: [
    { key: "dealType", label: "סוג עסקה", icon: "building", options: ["קנייה", "השכרה", "השקעה"] },
    { key: "budget", label: "תקציב", icon: "wallet", options: ["עד 1.8 מ׳ ₪", "1.8–2.5 מ׳ ₪", "2.5–3.5 מ׳ ₪", "מעל 3.5 מ׳ ₪"] },
    { key: "area", label: "אזור מבוקש", icon: "map-pin", options: ["רמת גן", "גבעתיים", "תל אביב", "הרצליה", "פתח תקווה"] },
  ],
  catalogIcon: "building",
  valueFactor: 0.02,
  brand: {
    accent: "#124e8f",
    accent2: "#1d9a89",
    warm: "#f3cb4d",
    ink: "#0b1118",
    bgFrom: "#cddfee",
    bgTo: "#e4efe2",
  },
  catalog: [
    { title: "4 חדרים · ז׳בוטינסקי, רמת גן", subtitle: "קומה 7, מעלית, מרפסת שמש", price: 2650000, priceSuffix: "₪", tags: ["למכירה"], meta: [{ label: "חדרים", value: "4" }, { label: "מ״ר", value: "104" }, { label: "קומה", value: "7" }, { label: "חניה", value: "1" }], photos: 18, status: "hot", sent: 58, dealValue: 53000 },
    { title: "פנטהאוז 5 חדרים · גבעתיים", subtitle: "גג פרטי, נוף פתוח", price: 4100000, priceSuffix: "₪", tags: ["למכירה"], meta: [{ label: "חדרים", value: "5" }, { label: "מ״ר", value: "142" }, { label: "קומה", value: "9" }, { label: "חניה", value: "2" }], photos: 24, status: "available", sent: 41, dealValue: 82000 },
    { title: "3 חדרים · שיכון עממי, פתח תקווה", subtitle: "משופצת, קרוב לרכבת", price: 6200, priceSuffix: "לחודש", tags: ["להשכרה"], meta: [{ label: "חדרים", value: "3" }, { label: "מ״ר", value: "78" }, { label: "קומה", value: "2" }, { label: "חניה", value: "—" }], photos: 12, status: "available", sent: 33, dealValue: 6200 },
    { title: "דירת גן 4 חדרים · הרצליה", subtitle: "חצר 60 מ״ר, שכונה שקטה", price: 3480000, priceSuffix: "₪", tags: ["למכירה"], meta: [{ label: "חדרים", value: "4" }, { label: "מ״ר", value: "118" }, { label: "קומה", value: "גן" }, { label: "חניה", value: "1" }], photos: 21, status: "reserved", sent: 27, dealValue: 70000 },
    { title: "סטודיו · לב תל אביב", subtitle: "מושקע לתשואה, מושכר", price: 1790000, priceSuffix: "₪", tags: ["השקעה"], meta: [{ label: "חדרים", value: "1" }, { label: "מ״ר", value: "36" }, { label: "קומה", value: "3" }, { label: "תשואה", value: "4.1%" }], photos: 14, status: "available", sent: 19, dealValue: 36000 },
    { title: "5 חדרים · קריית שאול, תל אביב", subtitle: "מעלית שבת, נוף לפארק", price: 3250000, priceSuffix: "₪", tags: ["למכירה"], meta: [{ label: "חדרים", value: "5" }, { label: "מ״ר", value: "128" }, { label: "קומה", value: "5" }, { label: "חניה", value: "2" }], photos: 19, status: "sold", sent: 46, dealValue: 65000 },
  ],
  appointmentLabels: ["סיור בנכס", "פגישת התאמה", "סיור שני", "חתימה על חוזה"],
  slotMinutes: 45,
  openers: [
    "שלום, ראיתי את הנכס {item}. עדיין פנוי?",
    "אפשר תמונות ופרטים על {item}?",
    "אפשר לקבוע סיור ב{item}?",
    "אשמח להתקדם עם {item}. מה המחיר הסופי?",
    "יש משהו דומה ל{item} באזור?",
  ],
  reply: "שלום! מצאתי התאמה: {item} — {price}. שולח תמונות ופרטים. אפשר סיור {slot}. מתאים?",
  confirm: "קבעתי סיור ל{slot}. שולח מיקום ופרטי מתאם הסיור.",
  close: "אתם מוזמנים להביא בן/בת זוג. אשלח תזכורת שעתיים לפני.",
  tags: ["מימון מאושר", "משקיע", "דחוף", "שוכר"],
  knowledge: ["כל הנכסים, תמונות ופרטים", "מחירים וסטטוס זמינות", "יומן סיורים", "תהליך קנייה ומשכנתא", "שכונות ותחבורה"],
}
