"""Regenerate src/brand/paths.ts from brand/*.svg (the SVGs stay the source of truth)."""
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
out = ["// Generated by scripts/build-brand-paths.py from brand/*.svg. Do not edit by hand.", ""]
for name, const in (("napuch-wordmark", "WORDMARK"), ("napuch-monogram", "MONOGRAM")):
    svg = (root / "brand" / f"{name}.svg").read_text()
    w, h = re.search(r'viewBox="0 0 (\d+) (\d+)"', svg).groups()
    paths = re.findall(r'<path id="([a-z]+)" d="([^"]+)"', svg)
    out.append(f"export const {const} = {{")
    out.append(f"  width: {w},")
    out.append(f"  height: {h},")
    out.append("  // Reading order, right to left.")
    out.append("  glyphs: [")
    for pid, d in paths:
        out.append(f'    {{ id: "{pid}", d: "{d}" }},')
    out.append("  ],")
    out.append("} as const")
    out.append("")
(root / "src" / "brand" / "paths.ts").write_text("\n".join(out))
print("wrote src/brand/paths.ts")
